using System.Threading.Tasks;
using MongoDB.Bson;
using Xunit;

namespace TrackableData.MongoDB.Tests
{
    public class PocoWithCustomIdMongoDbMapperTest : IClassFixture<MongoDbFixture>
    {
        private readonly MongoDbFixture _fixture;
        private readonly TrackablePocoMongoDbMapper<ITestPocoWithCustomId> _mapper;

        public PocoWithCustomIdMongoDbMapperTest(MongoDbFixture fixture)
        {
            _fixture = fixture;
            _mapper = new TrackablePocoMongoDbMapper<ITestPocoWithCustomId>();
        }

        [Fact]
        public async Task TestCustomId_CreateAndLoad()
        {
            var collection = _fixture.GetCollection("poco_customid");
            var person = new TrackableTestPocoWithCustomId
            {
                CustomId = UniqueInt64Id.GenerateNewId(),
                Name = "Testor",
                Age = 25
            };

            await _mapper.CreateAsync(collection, person);

            var loaded = await _mapper.LoadAsync(collection, person.CustomId);
            Assert.Equal(person.CustomId, loaded.CustomId);
            Assert.Equal("Testor", loaded.Name);
            Assert.Equal(25, loaded.Age);
        }
    }

    public class PocoWithObjectIdMongoDbMapperTest : IClassFixture<MongoDbFixture>
    {
        private readonly MongoDbFixture _fixture;
        private readonly TrackablePocoMongoDbMapper<ITestPocoWithObjectId> _mapper;

        public PocoWithObjectIdMongoDbMapperTest(MongoDbFixture fixture)
        {
            _fixture = fixture;
            _mapper = new TrackablePocoMongoDbMapper<ITestPocoWithObjectId>();
        }

        [Fact]
        public async Task TestObjectId_AutoGeneratedAndWrittenBack()
        {
            var collection = _fixture.GetCollection("poco_objectid");
            var person = new TrackableTestPocoWithObjectId { Name = "Bob", Age = 40 };
            Assert.Equal(ObjectId.Empty, person.Id);

            await _mapper.CreateAsync(collection, person);
            Assert.NotEqual(ObjectId.Empty, person.Id);

            var loaded = await _mapper.LoadAsync(collection, person.Id);
            Assert.Equal(person.Id, loaded.Id);
            Assert.Equal("Bob", loaded.Name);
        }
    }
}
