using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TrackableData.Generator
{
    internal class TrackableContainerEmitter
    {
        private readonly SourceProductionContext _context;
        private readonly INamedTypeSymbol _symbol;
        private readonly InterfaceDeclarationSyntax _syntax;

        public TrackableContainerEmitter(SourceProductionContext context, INamedTypeSymbol symbol, InterfaceDeclarationSyntax syntax)
        {
            _context = context;
            _symbol = symbol;
            _syntax = syntax;
        }

        public string? Emit()
        {
            var typeName = _symbol.Name;
            var className = "Trackable" + typeName.Substring(1);
            var trackerClassName = className + "Tracker";
            var namespaceName = EmitterHelper.GetFullNamespace(_symbol);
            var properties = EmitterHelper.GetProperties(_symbol);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using TrackableData;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(namespaceName) ? "" : "    ";
            var m = indent + "    ";
            var m2 = m + "    ";

            EmitContainerClass(sb, indent, m, m2, typeName, className, trackerClassName, properties);
            sb.AppendLine();
            EmitTrackerClass(sb, indent, m, m2, typeName, className, trackerClassName, properties);

            if (!string.IsNullOrEmpty(namespaceName))
                sb.AppendLine("}");

            return sb.ToString();
        }

        private void EmitContainerClass(StringBuilder sb, string indent, string m, string m2,
            string typeName, string className, string trackerClassName, System.Collections.Generic.List<PropertyInfo> properties)
        {
            sb.AppendLine($"{indent}public partial class {className} : {typeName}");
            sb.AppendLine($"{indent}{{");

            // Tracker
            sb.AppendLine($"{m}private {trackerClassName} _tracker;");
            sb.AppendLine();
            sb.AppendLine($"{m}public {trackerClassName} Tracker");
            sb.AppendLine($"{m}{{");
            sb.AppendLine($"{m2}get {{ return _tracker; }}");
            sb.AppendLine($"{m2}set");
            sb.AppendLine($"{m2}{{");
            sb.AppendLine($"{m2}    _tracker = value;");
            foreach (var p in properties)
                sb.AppendLine($"{m2}    {p.Name}.Tracker = value?.{p.Name}Tracker;");
            sb.AppendLine($"{m2}}}");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // Clone
            sb.AppendLine($"{m}public {className} Clone()");
            sb.AppendLine($"{m}{{");
            sb.AppendLine($"{m2}var o = new {className}();");
            foreach (var p in properties)
                sb.AppendLine($"{m2}o._{p.Name} = _{p.Name}?.Clone();");
            sb.AppendLine($"{m2}return o;");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // Changed
            sb.AppendLine($"{m}public bool Changed {{ get {{ return Tracker != null && Tracker.HasChange; }} }}");
            sb.AppendLine();

            // ITrackable.Tracker
            sb.AppendLine($"{m}ITracker ITrackable.Tracker");
            sb.AppendLine($"{m}{{");
            sb.AppendLine($"{m2}get {{ return Tracker; }}");
            sb.AppendLine($"{m2}set {{ Tracker = ({trackerClassName})value; }}");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // ITrackable<T>.Tracker
            sb.AppendLine($"{m}ITracker<{typeName}> ITrackable<{typeName}>.Tracker");
            sb.AppendLine($"{m}{{");
            sb.AppendLine($"{m2}get {{ return Tracker; }}");
            sb.AppendLine($"{m2}set {{ Tracker = ({trackerClassName})value; }}");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // ITrackableContainer<T>.Tracker
            sb.AppendLine($"{m}IContainerTracker<{typeName}> ITrackableContainer<{typeName}>.Tracker");
            sb.AppendLine($"{m}{{");
            sb.AppendLine($"{m2}get {{ return Tracker; }}");
            sb.AppendLine($"{m2}set {{ Tracker = ({trackerClassName})value; }}");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // ITrackable.Clone
            sb.AppendLine($"{m}ITrackable ITrackable.Clone() {{ return Clone(); }}");
            sb.AppendLine();

            // GetChildTrackable
            sb.AppendLine($"{m}public ITrackable GetChildTrackable(object name)");
            sb.AppendLine($"{m}{{");
            sb.AppendLine($"{m2}switch ((string)name)");
            sb.AppendLine($"{m2}{{");
            foreach (var p in properties)
                sb.AppendLine($"{m2}    case \"{p.Name}\": return {p.Name} as ITrackable;");
            sb.AppendLine($"{m2}    default: return null;");
            sb.AppendLine($"{m2}}}");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // GetChildTrackables
            sb.AppendLine($"{m}public IEnumerable<KeyValuePair<object, ITrackable>> GetChildTrackables(bool changedOnly = false)");
            sb.AppendLine($"{m}{{");
            foreach (var p in properties)
            {
                sb.AppendLine($"{m2}var trackable{p.Name} = {p.Name} as ITrackable;");
                sb.AppendLine($"{m2}if (trackable{p.Name} != null && (changedOnly == false || trackable{p.Name}.Changed))");
                sb.AppendLine($"{m2}    yield return new KeyValuePair<object, ITrackable>(\"{p.Name}\", trackable{p.Name});");
            }
            sb.AppendLine($"{m}}}");

            // Property backing fields and accessors
            foreach (var p in properties)
            {
                sb.AppendLine();
                sb.AppendLine($"{m}private {p.TypeName} _{p.Name} = new {p.TypeName}();");
                sb.AppendLine();
                sb.AppendLine($"{m}public {p.TypeName} {p.Name}");
                sb.AppendLine($"{m}{{");
                sb.AppendLine($"{m2}get {{ return _{p.Name}; }}");
                sb.AppendLine($"{m2}set");
                sb.AppendLine($"{m2}{{");
                sb.AppendLine($"{m2}    if (_{p.Name} != null) _{p.Name}.Tracker = null;");
                sb.AppendLine($"{m2}    if (value != null) value.Tracker = Tracker?.{p.Name}Tracker;");
                sb.AppendLine($"{m2}    _{p.Name} = value;");
                sb.AppendLine($"{m2}}}");
                sb.AppendLine($"{m}}}");
            }

            sb.AppendLine($"{indent}}}");
        }

        private void EmitTrackerClass(StringBuilder sb, string indent, string m, string m2,
            string typeName, string className, string trackerClassName, System.Collections.Generic.List<PropertyInfo> properties)
        {
            sb.AppendLine($"{indent}public class {trackerClassName} : IContainerTracker<{typeName}>");
            sb.AppendLine($"{indent}{{");

            // Property trackers
            foreach (var p in properties)
            {
                var trackerType = EmitterHelper.GetTrackerTypeName(p.TypeSymbol);
                sb.AppendLine($"{m}public {trackerType} {p.Name}Tracker {{ get; set; }} = new {trackerType}();");
            }
            sb.AppendLine();

            // HasChange
            sb.AppendLine($"{m}public bool HasChange");
            sb.AppendLine($"{m}{{");
            sb.AppendLine($"{m2}get");
            sb.AppendLine($"{m2}{{");
            sb.AppendLine($"{m2}    return");
            foreach (var p in properties)
                sb.AppendLine($"{m2}        ({p.Name}Tracker != null && {p.Name}Tracker.HasChange) ||");
            sb.AppendLine($"{m2}        false;");
            sb.AppendLine($"{m2}}}");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // HasChangeSet event
            sb.AppendLine($"{m}public event TrackerHasChangeSet HasChangeSet");
            sb.AppendLine($"{m}{{");
            sb.AppendLine($"{m2}add {{ throw new NotImplementedException(); }}");
            sb.AppendLine($"{m2}remove {{ throw new NotImplementedException(); }}");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // Clear
            sb.AppendLine($"{m}public void Clear()");
            sb.AppendLine($"{m}{{");
            foreach (var p in properties)
                sb.AppendLine($"{m2}{p.Name}Tracker?.Clear();");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // ApplyTo(object)
            sb.AppendLine($"{m}public void ApplyTo(object trackable) {{ ApplyTo(({typeName})trackable); }}");
            sb.AppendLine();

            // ApplyTo(T)
            sb.AppendLine($"{m}public void ApplyTo({typeName} trackable)");
            sb.AppendLine($"{m}{{");
            foreach (var p in properties)
                sb.AppendLine($"{m2}{p.Name}Tracker?.ApplyTo(trackable.{p.Name});");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // ApplyTo(ITracker)
            sb.AppendLine($"{m}public void ApplyTo(ITracker tracker) {{ ApplyTo(({trackerClassName})tracker); }}");
            sb.AppendLine($"{m}public void ApplyTo(ITracker<{typeName}> tracker) {{ ApplyTo(({trackerClassName})tracker); }}");
            sb.AppendLine();

            sb.AppendLine($"{m}public void ApplyTo({trackerClassName} tracker)");
            sb.AppendLine($"{m}{{");
            foreach (var p in properties)
                sb.AppendLine($"{m2}{p.Name}Tracker?.ApplyTo(tracker.{p.Name}Tracker);");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // RollbackTo(object)
            sb.AppendLine($"{m}public void RollbackTo(object trackable) {{ RollbackTo(({typeName})trackable); }}");
            sb.AppendLine();

            // RollbackTo(T)
            sb.AppendLine($"{m}public void RollbackTo({typeName} trackable)");
            sb.AppendLine($"{m}{{");
            foreach (var p in properties)
                sb.AppendLine($"{m2}{p.Name}Tracker?.RollbackTo(trackable.{p.Name});");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // RollbackTo(ITracker)
            sb.AppendLine($"{m}public void RollbackTo(ITracker tracker) {{ RollbackTo(({trackerClassName})tracker); }}");
            sb.AppendLine($"{m}public void RollbackTo(ITracker<{typeName}> tracker) {{ RollbackTo(({trackerClassName})tracker); }}");
            sb.AppendLine();

            sb.AppendLine($"{m}public void RollbackTo({trackerClassName} tracker)");
            sb.AppendLine($"{m}{{");
            foreach (var p in properties)
                sb.AppendLine($"{m2}{p.Name}Tracker?.RollbackTo(tracker.{p.Name}Tracker);");
            sb.AppendLine($"{m}}}");

            sb.AppendLine($"{indent}}}");
        }
    }
}
