using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TrackableData.Generator
{
    internal class TrackablePocoEmitter
    {
        private readonly SourceProductionContext _context;
        private readonly INamedTypeSymbol _symbol;
        private readonly InterfaceDeclarationSyntax _syntax;

        public TrackablePocoEmitter(SourceProductionContext context, INamedTypeSymbol symbol, InterfaceDeclarationSyntax syntax)
        {
            _context = context;
            _symbol = symbol;
            _syntax = syntax;
        }

        public string? Emit()
        {
            var typeName = _symbol.Name;
            var className = "Trackable" + typeName.Substring(1);
            var namespaceName = EmitterHelper.GetFullNamespace(_symbol);
            var properties = EmitterHelper.GetProperties(_symbol);
            var trackableProperties = properties.Where(p => p.IsTrackable).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine("using TrackableData;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(namespaceName) ? "" : "    ";

            // Class declaration
            sb.AppendLine($"{indent}public partial class {className} : {typeName}");
            sb.AppendLine($"{indent}{{");
            var m = indent + "    ";
            var m2 = m + "    ";

            // Tracker property
            sb.AppendLine($"{m}public IPocoTracker<{typeName}> Tracker {{ get; set; }}");
            sb.AppendLine();

            // Clone method
            sb.AppendLine($"{m}public {className} Clone()");
            sb.AppendLine($"{m}{{");
            sb.AppendLine($"{m2}var o = new {className}();");
            foreach (var p in properties)
            {
                if (p.IsTrackable)
                    sb.AppendLine($"{m2}o._{p.Name} = _{p.Name}?.Clone();");
                else
                    sb.AppendLine($"{m2}o._{p.Name} = _{p.Name};");
            }
            sb.AppendLine($"{m2}return o;");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // Changed property
            sb.AppendLine($"{m}public bool Changed {{ get {{ return Tracker != null && Tracker.HasChange; }} }}");
            sb.AppendLine();

            // ITrackable.Tracker
            sb.AppendLine($"{m}ITracker ITrackable.Tracker");
            sb.AppendLine($"{m}{{");
            sb.AppendLine($"{m2}get {{ return Tracker; }}");
            sb.AppendLine($"{m2}set {{ Tracker = (IPocoTracker<{typeName}>)value; }}");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // ITrackable<T>.Tracker
            sb.AppendLine($"{m}ITracker<{typeName}> ITrackable<{typeName}>.Tracker");
            sb.AppendLine($"{m}{{");
            sb.AppendLine($"{m2}get {{ return Tracker; }}");
            sb.AppendLine($"{m2}set {{ Tracker = (IPocoTracker<{typeName}>)value; }}");
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // ITrackable.Clone
            sb.AppendLine($"{m}ITrackable ITrackable.Clone() {{ return Clone(); }}");
            sb.AppendLine();

            // GetChildTrackable
            sb.AppendLine($"{m}public ITrackable GetChildTrackable(object name)");
            sb.AppendLine($"{m}{{");
            if (trackableProperties.Any())
            {
                sb.AppendLine($"{m2}switch ((string)name)");
                sb.AppendLine($"{m2}{{");
                foreach (var p in trackableProperties)
                    sb.AppendLine($"{m2}    case \"{p.Name}\": return {p.Name} as ITrackable;");
                sb.AppendLine($"{m2}    default: return null;");
                sb.AppendLine($"{m2}}}");
            }
            else
            {
                sb.AppendLine($"{m2}return null;");
            }
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // GetChildTrackables
            sb.AppendLine($"{m}public IEnumerable<KeyValuePair<object, ITrackable>> GetChildTrackables(bool changedOnly = false)");
            sb.AppendLine($"{m}{{");
            if (trackableProperties.Any())
            {
                foreach (var p in trackableProperties)
                {
                    sb.AppendLine($"{m2}var trackable{p.Name} = {p.Name} as ITrackable;");
                    sb.AppendLine($"{m2}if (trackable{p.Name} != null && (changedOnly == false || trackable{p.Name}.Changed))");
                    sb.AppendLine($"{m2}    yield return new KeyValuePair<object, ITrackable>(\"{p.Name}\", trackable{p.Name});");
                }
            }
            else
            {
                sb.AppendLine($"{m2}yield break;");
            }
            sb.AppendLine($"{m}}}");
            sb.AppendLine();

            // PropertyTable
            sb.AppendLine($"{m}public static class PropertyTable");
            sb.AppendLine($"{m}{{");
            foreach (var p in properties)
                sb.AppendLine($"{m2}public static readonly PropertyInfo {p.Name} = typeof({typeName}).GetProperty(\"{p.Name}\");");
            sb.AppendLine($"{m}}}");

            // Property backing fields and accessors
            foreach (var p in properties)
            {
                sb.AppendLine();
                sb.AppendLine($"{m}private {p.TypeName} _{p.Name};");
                sb.AppendLine();
                sb.AppendLine($"{m}public {p.TypeName} {p.Name}");
                sb.AppendLine($"{m}{{");
                sb.AppendLine($"{m2}get {{ return _{p.Name}; }}");
                sb.AppendLine($"{m2}set");
                sb.AppendLine($"{m2}{{");
                sb.AppendLine($"{m2}    if (Tracker != null && {p.Name} != value)");
                sb.AppendLine($"{m2}        Tracker.TrackSet(PropertyTable.{p.Name}, _{p.Name}, value);");
                sb.AppendLine($"{m2}    _{p.Name} = value;");
                sb.AppendLine($"{m2}}}");
                sb.AppendLine($"{m}}}");
            }

            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(namespaceName))
                sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
